# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
# Uncomment the lines below to configure your website in a second language.

zh:
 languageCode: zh-Hans
 contentDir: content/zh
 title: 苏黎世学联
 params:
   description: 苏黎世学联

en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
