# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 服务
    url: service
    identifier: service
    weight: 10
  - name: 新生答疑会录屏
    parent: service
    url: service/guide
    weight: 11
  - name: 新生手册
    parent: service
    url: service/booklet
    weight: 12
  - name: 学联微信公众号
    parent: service
    url: service/wechat
    weight: 13
  - name: 学联小红书
    parent: service
    url: service/redbook
    weight: 14
  - name: 学联论坛
    parent: service
    url: service/forum #https://forum.acssz.org
    weight: 15
  - name: 学联卡小程序
    parent: service
    url: service/miniprogram
    weight: 16
  - name: 学联专属Sunrise YOL折扣
    parent: service
    url: service/sunrise
    weight: 17
  - name: 学联专属Swisscare折扣
    parent: service
    url: service/swisscare
    weight: 18
  - name: 学联伙伴intermezzo租房
    parent: service
    url: service/intermezzo
    weight: 19
  - name: 活动
    identifier: event
    url: event
    weight: 20
  - name: 2024
    parent: event
    url: event/2024/
    weight: 21
  - name: 2022
    parent: event
    url: event/2022/
    weight: 22
  - name: 2021
    parent: event
    url: event/2021/
    weight: 23
  - name: 2020
    parent: event
    url: event/2020/
    weight: 24
  - name: 2019
    parent: event
    url: event/2019/
    weight: 25
  - name: 2018
    parent: event
    url: event/2018/
    weight: 26
  - name: 伙伴
    identifier: partner
    url: partner
    weight: 30
  - name: 赞助伙伴
    parent: partner
    url: partner/sponsorship
    weight: 31
  - name: 合作伙伴
    parent: partner
    url: partner/collaboration
    weight: 32
  - name: 关于
    identifier: about
    url: about
    weight: 40
  - name: 学联简介
    parent: about
    url: about/intro/
    weight: 42
  - name: 团队信息
    parent: about
    url: about/people/
    weight: 43
  - name: 部门结构
    parent: about
    url: about/group_archi/
    weight: 44
  - name: 联系学联
    parent: about
    url: about/contact/
    weight: 45
