# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Summary of Services
    url: service
    identifier: service
    weight: 10
  - name: Useful Information
    parent: service
    url: service/booklet
    weight: 11
  - name: Q&A for Freshmen
    parent: service
    url: service/qa
    weight: 12
  - name: Event Information
    identifier: event
    url: event
    weight: 20
  - name: Event Notification
    parent: event
    url: event/new/
    weight: 21
  - name: Event Review
    parent: event
    url: event/past/
    weight: 22
  - name: Cooperative Partner
    identifier: partner
    url: partner
    weight: 30
  - name: Business Cooperation
    parent: partner
    url: partner/business/
    weight: 31
  - name: Membership Card
    parent: partner
    url: partner/card/
    weight: 32
  - name: About Us
    identifier: about
    url: about
    weight: 40
  - name: Group Information
    parent: about
    url: about/people/
    weight: 41
  - name: Department Introduction
    parent: about
    url: about/group/
    weight: 42
  - name: Contact Us
    parent: about
    url: about/contact/
    weight: 43
